name: Push to vps
on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh debian@141.94.250.104
      - run: cd /home/debian/DesAnes4Green
      - run: git pull
      - run: yarn build
      - run: sudo mv ./dist/* /var/www/html
